<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>EPrescriptions.Domain</RootNamespace>
    <AssemblyName>EPrescriptions.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EPrescriptions.Core\EPrescriptions.Core.csproj" />
  </ItemGroup>
</Project>
